
INSERT INTO public.epi_items (code, unit, name, category, manufacturer, ca_number, ca_valid_until, useful_life_days, size_required, active, notes) VALUES
('UNI001','UN','Boné','UNIFORME','','',NULL,NULL,false,true,'Tamanho único ou ajustável'),
('UNI002','UN','Calça','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI003','UN','Calça Sarja','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI004','UN','Calça Tática','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI005','UN','Calça Tática ASP','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI006','UN','Camisa Manga Longa','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI007','UN','Camisa Social','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI008','UN','Camiseta','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI009','UN','Camiseta Gola Polo','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI010','UN','Camiseta Manga Curta','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI011','PAR','Coturno','UNIFORME','','',NULL,NULL,true,true,'Numeração: 35 ao 46'),
('UNI012','UN','Jaqueta','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI013','UN','Jaleco','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI014','UN','Suéter','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('UNI015','UN','Colete Tático','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('EPI001','UN','Abafador de Ruídos Tipo Concha','EPI','','',NULL,NULL,false,true,'Exige CA conforme fabricante/modelo'),
('EPI002','PAR','Bota','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46'),
('EPI003','PAR','Bota de Segurança','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46; exige CA'),
('EPI004','PAR','Botina','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46; exige CA se for de segurança'),
('EPI005','PAR','Calçado de Segurança','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46'),
('EPI006','UN','Capa de Chuva','EPI','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('EPI007','UN','Capacete','EPI','','',NULL,NULL,false,true,'Exige CA conforme fabricante/modelo'),
('EPI008','UN','Capacete de Segurança com Jugular','EPI','','',NULL,NULL,false,true,'Exige CA conforme fabricante/modelo'),
('EPI009','UN','Colete Refletivo','EPI','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('EPI010','UN','Jugular para Capacete','EPI','','',NULL,NULL,false,true,'Acessório do capacete'),
('EPI011','PAR','Luvas','EPI','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG; exige CA conforme modelo'),
('EPI012','UN','Máscara','EPI','','',NULL,NULL,false,true,'Validar modelo reutilizável'),
('EPI013','UN','Máscara Descartável','EPI','','',NULL,NULL,false,true,'Item de consumo'),
('EPI014','UN','Óculos de Proteção','EPI','','',NULL,NULL,false,true,'Exige CA conforme fabricante/modelo'),
('EPI015','UN','Protetor Auricular','EPI','','',NULL,NULL,false,true,'Padronizar com protetor auditivo se quiser unificar'),
('EPI016','PAR','Protetor Auditivo','EPI','','',NULL,NULL,false,true,'Pode unificar com protetor auricular'),
('EPI017','UN','Respirador','EPI','','',NULL,NULL,false,true,'Exige CA conforme classe/modelo'),
('EPI018','PAR','Sapato','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46'),
('EPI019','PAR','Sapato Elástico Eletricista','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46'),
('EPI020','UN','Talabarte de Segurança','EPI','','',NULL,NULL,false,true,'Exige CA conforme fabricante/modelo'),
('APO001','UN','Lanterna para o Posto','APOIO OPERACIONAL','','',NULL,NULL,false,true,'Item de apoio para portaria'),
('UNI016','UN','Crachá Funcional','UNIFORME','','',NULL,NULL,false,true,'Recomendado para escritório, recepção e portaria'),
('UNI017','UN','Colete Identificador','UNIFORME','','',NULL,NULL,true,true,'Tamanhos: P, M, G, GG, XG'),
('EPI021','UN','Protetor Solar','EPI','','',NULL,NULL,false,true,'Útil para trabalho externo e portaria'),
('EPI022','PAR','Calçado Antiderrapante','EPI','','',NULL,NULL,true,true,'Numeração: 35 ao 46');
