export const DOCUMENT_FILE_TYPES = new Set([
  'RG_CNH',
  'CPF',
  'CTPS',
  'RESIDENCIA',
  'CERTIDAO',
  'TITULO_ELEITOR',
  'QUITACAO_ELEITORAL',
  'RESERVISTA',
  'PIS_PASEP',
  'DEP_CERTIDAO',
  'DEP_CPF',
  'DEP_VACINA',
  'DEP_MATRICULA',
  'DEP_LAUDO',
]);

export const SIGNATURE_FILE_TYPES = new Set([
  'CONTRATO_TRABALHO_SIGNED',
  'FICHA_REGISTRO_SIGNED',
  'DECLARACAO_DEPENDENTES_IRRF_SIGNED',
  'AUTORIZACAO_DESCONTO_VT_SIGNED',
  'TERMO_RESPONSABILIDADE_EQUIP_SIGNED',
  'TERMO_CONFIDENCIALIDADE_SIGNED',
]);
