/**
 * Lista predefinida de cargos/funções para o módulo de admissões.
 * Pode ser selecionado via combobox ou digitado manualmente.
 */
export const CARGOS_PREDEFINIDOS: string[] = [
  // Engenharia e Arquitetura
  'Arquiteto de edificações',
  'Arquiteto de interiores',
  'Arquiteto paisagista',
  'Arquiteto urbanista',
  'Desenhista projetista de arquitetura',
  'Desenhista projetista de construção civil',
  'Desenhista projetista de eletricidade',
  'Desenhista técnico (construção civil)',
  'Desenhista técnico (instalações hidrossanitárias)',
  'Eletrotécnico',
  'Engenheiro ambiental',
  'Engenheiro civil',
  'Engenheiro civil (edificações)',
  'Engenheiro civil (estruturas metálicas)',
  'Engenheiro civil (geotécnia)',
  'Engenheiro civil (hidráulica)',
  'Engenheiro civil (rodovias)',
  'Engenheiro civil (saneamento)',
  'Engenheiro civil (transportes e trânsito)',
  'Engenheiro de controle de qualidade',
  'Engenheiro de produção',
  'Engenheiro de redes de comunicação',
  'Engenheiro de segurança do trabalho',
  'Engenheiro de telecomunicações',
  'Engenheiro eletricista',
  'Engenheiro eletricista de manutenção',
  'Engenheiro eletricista de projetos',
  'Engenheiro eletrônico',
  'Engenheiro eletrônico de manutenção',
  'Engenheiro eletrônico de projetos',
  'Engenheiro mecânico',
  'Engenheiro mecânico industrial',
  'Engenheiro projetista de telecomunicações',
  'Tecnólogo em construção civil',
  'Tecnólogo em segurança do trabalho',
  'Topógrafo',
  'Técnico de estradas',
  'Técnico de obras civis',
  'Técnico de saneamento',
  'Técnico eletricista',
  'Técnico em agrimensura',
  'Técnico em segurança do trabalho',
  // Construção Civil
  'Armador de estrutura de concreto',
  'Armador de estrutura de concreto armado',
  'Assentador de canalização (edificações)',
  'Assentador de revestimentos cerâmicos',
  'Carpinteiro',
  'Carpinteiro de fôrmas para concreto',
  'Carpinteiro de obras',
  'Demolidor de edificações',
  'Eletricista de instalações',
  'Eletricista de instalações (edifícios)',
  'Encanador',
  'Fiscal de pátio de usina de concreto',
  'Gerente de produção e operações da construção civil e obras públicas',
  'Gesseiro',
  'Inspetor de terraplenagem',
  'Instalador de sistemas fotovoltaicos',
  'Instalador de tubulações',
  'Marmorista (construção)',
  'Mestre (construção civil)',
  'Montador de andaimes (edificações)',
  'Operador de martelete',
  'Pedreiro',
  'Pedreiro de edificações',
  'Pintor de obras',
  'Poceiro (edificações)',
  'Rejuntador de revestimentos',
  'Serralheiro',
  'Servente de obras',
  'Supervisor de usina de concreto',
  'Telhador (telhas de argila e materiais similares)',
  'Telhador (telhas metálicas)',
  'Vidraceiro',
  'Vidraceiro (edificações)',
  // Segurança
  'Agente de portaria',
  'Agente de segurança',
  'Gestor em segurança',
  'Instalador de sistemas eletroeletrônicos de segurança',
  'Mantenedor de sistemas eletroeletrônicos de segurança',
  'Monitor de sistemas eletrônicos de segurança externo',
  'Monitor de sistemas eletrônicos de segurança interno',
  'Porteiro de edifícios',
  'Supervisor de vigilantes',
  'Vigia',
  'Vigilante',
  // Limpeza e Conservação
  'Faxineiro',
  'Jardineiro',
  'Limpador de fachadas',
  'Limpador de piscinas',
  'Limpador de vidros',
  'Trabalhador da manutenção de edificações',
  'Trabalhador de serviços de limpeza e conservação de áreas públicas',
  'Varredor de rua',
  // Facilities
  'Administrador de edifícios',
  'Auxiliar de manutenção predial',
  'Eletricista de manutenção eletroeletrônica',
  'Garagista',
  'Gerente de facility management',
  'Mecânico de manutenção e instalação de aparelhos de climatização e refrigeração',
  'Técnico de manutenção elétrica',
  'Técnico de manutenção elétrica de máquina',
  'Zelador de edifício',
  // Administrativo
  'Administrador',
  'Analista de folha de pagamento',
  'Analista de recursos humanos',
  'Assistente administrativo',
  'Auxiliar de contabilidade',
  'Auxiliar de escritório',
  'Auxiliar de faturamento',
  'Auxiliar de pessoal',
  'Contador',
  'Diretor administrativo',
  'Diretor administrativo e financeiro',
  'Diretor de recursos humanos',
  'Diretor de relações de trabalho',
  'Diretor financeiro',
  'Gerente administrativo',
  'Gerente de departamento pessoal',
  'Gerente de recursos humanos',
  'Gerente financeiro',
  'Recepcionista, em geral',
  'Secretária(o) executiva(o)',
  'Supervisor administrativo',
  'Tecnólogo em gestão administrativo- financeira',
  // Logística e Comercial
  'Agente de vendas de serviços',
  'Almoxarife',
  'Analista de gestão de estoque',
  'Analista de logistica',
  'Analista de negócios',
  'Analista de pesquisa de mercado',
  'Analista de planejamento de materias',
  'Analista de projetos logisticos',
  'Apontador de mão-de-obra',
  'Armazenista',
  'Assistente de vendas',
  'Auxiliar de logistica',
  'Comprador',
  'Conferente de carga e descarga',
  'Conferente mercadoria (exceto carga e descarga)',
  'Diretor comercial',
  'Diretor de marketing',
  'Estoquista',
  'Expedidor de mercadorias',
  'Gerente comercial',
  'Gerente de marketing',
  'Gerente de vendas',
  'Motorista de caminhão (rotas regionais e internacionais)',
  'Motorista de carro de passeio',
  'Motorista de furgão ou veículo similar',
  'Supervisor de almoxarifado',
  'Supervisor de compras',
  'Supervisor de logística',
  'Supervisor de orçamento',
  'Técnico de vendas',
  'Técnico em atendimento e vendas',
  'Vendedor pracista',
];
