// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// [Checkpoint A / P1-05] Sem fallback embutido: cada ambiente precisa declarar
// a sua própria configuração pública. Se faltar, a aplicação mostra a tela de
// erro de configuração em vez de conectar silenciosamente em outro ambiente.
const isTest = import.meta.env.MODE === 'test';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
  || (isTest ? 'http://127.0.0.1:54321' : '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  || (isTest ? 'test-publishable-key' : '');

export const missingSupabaseEnvironment = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter((name): name is string => Boolean(name));

// Placeholders inertes apenas para permitir a construção do módulo; nenhuma
// requisição é feita porque a aplicação bloqueia na tela de configuração.
const CLIENT_URL = SUPABASE_URL || 'http://configuracao-ausente.invalid';
const CLIENT_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || 'configuracao-ausente';


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(CLIENT_URL, CLIENT_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
