// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Configuração pública do ambiente. Em teste usamos o Supabase local; nos
// demais ambientes as variáveis VITE_* têm prioridade e, quando ausentes na
// publicação, caímos na configuração pública oficial deste projeto (URL e
// chave publicável são valores públicos protegidos por RLS).
const isTest = import.meta.env.MODE === 'test';
const FALLBACK_URL = isTest ? 'http://127.0.0.1:54321' : 'https://zeaerqlvhrbcuubueolh.supabase.co';
const FALLBACK_PUBLISHABLE_KEY = isTest
  ? 'test-publishable-key'
  : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYWVycWx2aHJiY3V1YnVlb2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzgyMjMsImV4cCI6MjA4ODA1NDIyM30.NjYxq4HgiCBBA5ll39h620NzmnKzau41GMDAEdWIR7c';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_PUBLISHABLE_KEY;

export const missingSupabaseEnvironment = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter((name): name is string => Boolean(name));

// Placeholders inertes apenas para permitir a construção do módulo; nenhuma
// requisição é feita porque a aplicação bloqueia na tela de configuração.
const CLIENT_URL = SUPABASE_URL || 'http://configuracao-ausente.invalid';
const CLIENT_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || 'configuracao-ausente';


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(CLIENT_URL, CLIENT_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
